name: SonarCloud

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud_branch:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore Dependencies
        run: dotnet restore ./Streetcode/Streetcode.sln

      - name: Install xmldocmd
        run: dotnet tool install xmldocmd -g

      - name: Build
        run: dotnet build ./Streetcode/Streetcode.sln --configuration Release --no-restore

      - name: Test and Code Coverage
        run: dotnet-coverage collect "dotnet test ./Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj --configuration Release --results-directory ./coverage --logger trx" -f xml -o coverage.xml

      - name: SonarScanner Analysis
        id: sonar
        run: |
         dotnet sonarscanner begin /k:"petrobubka_StreetCode_sonar" /o:"petrobubka" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths="**/coverage.xml"
         dotnet build ./Streetcode/Streetcode.sln --configuration Release
         dotnet test ./Streetcode/Streetcode.XUnitTest/Streetcode.XUnitTest.csproj --configuration Release --no-build --verbosity normal
         dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Publish Code Coverage Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Code Coverage Report
          path: |
            ./Streetcode/Streetcode.XUnitTest/coverage/coverage.xml
